{"AMODE"     : "AMODE(24 | 31 | 64 | ANY | MIN)",
 "RMODE"     : "RMODE(MIN | 24 | ANY | 31 | SPLIT [,INITIAL | COMPAT])",
 "COMPPARM"  : "LIST,MAP,RENT,COMPAT(PM5),XREF(SHORT),NONUMBER,SOURCE",
 "COBOLVER"  : "V4,V6",
 "PROCESSOR" : "ENDEVOR-IBM370-COBOL",
 "ANYOPTION" : "NOCOMPILE",
 "DBRM"      : "RLAM.PROD.DBRMLIB",
 "DB2OWNER"  : "IBMUSER",
 "QUALIFIER" : "DB2ABC"
}


